In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [26]:
def calculatemean():
    mean_matrix = np.zeros((10, 784))
    number = 1
    for images in range (0,10):  
        for num in range (0,240):   
            img = plt.imread("Train/"+str(number)+".jpg").ravel()
            number+=1
            for pixels in range (0,784):              
                mean_matrix[images][pixels]+=img[pixels]
    mean_matrix = mean_matrix/240 
    return mean_matrix
def calculateVariance(mean_matrix):
    var_matrix = np.zeros((10, 784))
    number = 1
    for images in range (0,10):  
        for num in range (0,240):   
            img = plt.imread("Train/"+str(number)+".jpg").ravel()
            number+=1
            for pixels in range (0,784):              
                var_matrix[images][pixels]+=((img[pixels]-mean_matrix[images][pixels])*(img[pixels]-mean_matrix[images][pixels]))
    var_matrix = var_matrix/240
    for i in range (0,10): 
        for j in range (0,784):
            if (var_matrix[i][j]<0.01):
                var_matrix[i][j]=0.01
    return var_matrix 
mean_matrix =calculatemean()
print(calculatemean())
print("======")
print(calculateVariance(mean_matrix))


[[0.03333333 0.17916667 0.14583333 ... 0.         0.         0.        ]
 [0.0125     0.         0.04166667 ... 0.         0.         0.        ]
 [0.51666667 0.575      0.5375     ... 0.         0.         0.        ]
 ...
 [0.56666667 0.29166667 0.45416667 ... 0.         0.         0.        ]
 [0.17083333 0.19166667 0.0625     ... 0.         0.         0.        ]
 [0.0375     0.05416667 0.075      ... 0.0125     0.02083333 0.02083333]]
[[0.07388889 1.08039931 0.84956597 ... 0.01       0.01       0.01      ]
 [0.03734375 0.01       0.21493056 ... 0.01       0.01       0.01      ]
 [2.94972222 4.38604167 5.34859375 ... 0.01       0.01       0.01      ]
 ...
 [3.57055556 1.26493056 2.63956597 ... 0.01       0.01       0.01      ]
 [0.84998264 1.32159722 0.15859375 ... 0.01       0.01       0.01      ]
 [0.26942708 0.30123264 0.43604167 ... 0.03734375 0.10373264 0.10373264]]


In [12]:
number= 0+1
img = plt.imread("Train/"+str(number)+".jpg").ravel()
image=np.zeros(784)
#print(img)
for i in range (0,784):       
        image [i] = (img[i]/255)
c = np.zeros((10, 784))
print(c)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
